### PR TITLE
First edition of the storyboard-scene microservices

### PR DESCRIPTION
**Pull request by BlaidddDrwg**
This set of microservices has been created using micro and micro-api - microservices frameworks for nodejs. While they are quite neat, there are a number of problems that need to be resolved:

1. While they support the 'get' request fairly well, the 'post' function is patch. I was unable to pull ANY of the parameters from a POST submission, into the processing engine.
2. Without POST support, we cannot have a true REST API - I have added a few elements of the service to show how it can and should be done, and I think these services that have been implemented should be enough for the post part. But the are not true REST.
3. If it has to be done right, we have to figure out how to doa POST and retrieve the post parametersin micro (or micro-api),so that we are able to process it properly.

### CODE REVIEW

**Comment by parkedwards** [comment]
Hey Vikram - as discussed, let's look into parsing the POST request body from within the API layer first before making a subsequent POST request to the MS layer

**Comment by BlaidddDrwg** [comment]
Added .gitignore and removed the node_modules library directory from version control.

**Comment by BlaidddDrwg** [comment]
Not sure if/what I have to do to return this to 'review' for you, Eddie...

**Comment by parkedwards** [comment]
Im going to go ahead and merge this so we can get started, we can adjust directory structure down the line

**Comment by BlaidddDrwg** [comment]
Okay, I think I've made most of the changes requested, so I'm closing/merging this pull request.

**Pull request merged**
